version: "3.7"

services:
  user-service:
    image: user-service:v1
    container_name: user-service
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/user
      SPRING_FLYWAY_URL: jdbc:postgresql://database:5432/user
    depends_on:
      - database
    deploy:
      restart_policy:
        delay: 5s

  email-service:
    image: email:v1
    container_name: email-service
    ports:
      - 8081:8081

  database:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asd1028.
      POSTGRES_DB: user



