apiVersion: v1
kind: Service
metadata:
  labels:
    service: email-service
  name: email-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: email-service
  type: NodePort
status:
  loadBalancer: {}


